name: Node CI

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 4.4
          mongodb-port: 27017

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run ci:test

      - name: Generate output
        run: npm run ci:build
